### PR TITLE
Update to v3.2.4

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
This should probably be fixed up to use `pip` and swap out the `build` for `host` sections.

**Pull request merged**
